[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
favourites = "HGLdBayTFRKtGTcdSJjm2S6btqfW4TbqYdkeawK3BihN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Awesome_webber\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
