[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q3 = "CefwGwxEL3araDxZTWBoe9kcgCZB88X8DpKbYH7s2BGm"

[programs.devnet]
anchor_vault_q3 = "CefwGwxEL3araDxZTWBoe9kcgCZB88X8DpKbYH7s2BGm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
